service: api-js-core

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  region: ${env:AWS_REGION}
  stage: ${env:STAGE}
  httpApi:
    cors: true
    name: ${self:service}-${self:provider.stage}-api
  environment:
    ENV_LOAN_TABLE_NAME: !Ref LoanTable
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:*
            - s3:*
            - dynamodb:*
            - ssm:*
            - sqs:*
          Resource: "*"

package:
  individually: true
  patterns: ["!**/*", "package.json"]

custom:
  version: "v1"
  prefix: ${self:service}-${self:provider.stage}

functions:
  createLoan:
    handler: dist/create-loan.handler
    package:
      patterns: dist/create-loan.js
    events:
      - httpApi:
          method: POST
          path: /${self:custom.version}/loans

resources:
  Resources:
    LoanTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:custom.prefix}-loantable
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        BillingMode: "PAY_PER_REQUEST"
