service: api-js-core

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  region: ${env:AWS_REGION}
  stage: ${env:STAGE}

package:
  individually: true
  patterns: "!**/*"

functions:
  hello:
    handler: dist/hello/index.handler
    package:
      patterns: "dist/hello/**"
  world:
    handler: dist/world/index.handler
    package:
      patterns: "dist/world/**"
