service: api-js-core

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  region: ${env:AWS_REGION}
  stage: ${env:STAGE}

package:
  individually: true
  patterns:
    - "!**/*"

functions:
  hello:
    handler: dist/hello.handler
    package:
      patterns: "dist/hello.js"
  world:
    handler: dist/world.handler
    package:
      patterns: "dist/world.js"
  dummy:
    handler: dist/dummy.handler
    package:
      patterns: "dist/dummy.js"
